# Generated by Django 6.0.6 on 2026-06-08 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('REP', 'Representante'), ('VOC', 'Vocero'), ('SUB', 'Subvocero')], max_length=3)),
                ('ficha', models.CharField(blank=True, help_text='Ficha solo para vocero y subvocero', max_length=12, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(blank=True, help_text='Ficha del grupo de aprendices', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REP', 'Representante'), ('VOC', 'Vocero'), ('SUB', 'Subvocero')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.candidacy')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.profile')),
            ],
            options={
                'unique_together': {('voter', 'role')},
            },
        ),
    ]
