# Generated by Django 6.0.6 on 2026-06-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidacy',
            options={'ordering': ['role', 'name'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AddField(
            model_name='candidacy',
            name='proposals',
            field=models.TextField(blank=True, help_text='Propuestas separadas por saltos de línea'),
        ),
    ]
