# Generated by Django 6.0.6 on 2026-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_alter_candidacy_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacy',
            name='proposal_image',
            field=models.CharField(blank=True, help_text='Ruta de imagen para las propuestas, por ejemplo elecciones/img/proposal-community.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='description',
            field=models.TextField(blank=True, help_text='Una breve descripción personal del candidato', verbose_name='Biografía'),
        ),
    ]
