# Generated by Django 6.0.6 on 2026-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Foto de perfil del candidato', null=True, upload_to='candidates/'),
        ),
    ]
